version: "3"
services:
  textUtilsBot:
    build: .
    image: kozalo/textutilsbot
    container_name: textutilsbot
    hostname: testUtilsBot
    working_dir: /home/textUtilsBot
    restart: always
    volumes:
    - "./app/data:/home/textUtilsBot/app/data"
    - "/tmp:/tmp"
